title: Amzn Partners
description: Blog Post Description

url: http://https://amznpartners.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: Sobre
    url: /about
  - title: Contato
    url: /contact

social:
  github: amznpartners
  twitter: amznpartners
  instagram: amznpartners
  facebook: amznpartners
  email: contato@amznpartners.com

google_analytics: "UA-58263416-1"
